_BASE_: "../Base.yaml"

DATASETS:
  TRAIN: ("mpsc_poly_train_pos",)
  TEST: ("mpsc_poly_test",)  # or "inversetext_test", "totaltext_poly_test_rotate"

MODEL:
  WEIGHTS: "output/model_final.pth"  # or the provided pre-trained model

SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 5e-5
  LR_BACKBONE: 5e-6
  WARMUP_ITERS: 0
  STEPS: (16000,)
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 1000

TEST:
  EVAL_PERIOD: 1000

OUTPUT_DIR: "output/r_50_poly/mpsc/8th_trial" #fixed annotation bug